/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f103xx.h"
#include "stm32f103xx_gpio_driver.h"


void delay(void)
{
	for(uint32_t i=0; i<50/2; i++);
}

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	GPIO_Handle_t GpioLed;
	memset(&GpioLed,0,sizeof(GpioLed));
	GpioLed.pGPIOx = GPIOC;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_13;
	GpioLed.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_OUT_50Mhz;
	GpioLed.GPIO_PinConfig.GPIO_PinOpType= GPIO_OP_TYPE_OPENDRAIN;

	GPIO_Handle_t GpioButton;
	GpioButton.pGPIOx = GPIOA;
	GpioButton.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_0;
	GpioButton.GPIO_PinConfig.GPIO_PinMode= GPIO_MODE_IN;
	GpioButton.GPIO_PinConfig.GPIO_PinInType= GPIO_IN_TYPE_PULLUP;

	GPIOC_PCLK_EN();
	GPIOA_PCLK_EN();

	GPIO_Init(&GpioLed);
	GPIO_Init(&GpioButton);

	while(1)
	{
		if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0))
		{
			GPIO_ToggleOutputPin(GPIOC, GPIO_PIN_NO_13);
			delay();
		}
		else
		{
			GPIO_WriteToOutputPin(GPIOC, GPIO_PIN_NO_13, DISABLE);
		}

	}

}
